---
- name: run openscap
  hosts: all
  become: yes

  tasks:
    - name: run openscap to evaluate compliance
      ansible.builtin.command: oscap xccdf eval \
        --profile xccdf_org.ssgproject.content_profile_cis \
        --report report.html \
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      ignore_errors: false
