---
- hosts: all  
  become: true

  vars:
    cis_remediation:
      - '1.1.1.1'
      - '1.1.1.2'
      - '1.1.2.1'
      - '1.1.2.2'
      - '1.1.2.3'
      - '1.1.2.4'
      - '1.1.3.1'
      - '1.1.3.2'
      - '1.1.3.3'
      - '1.1.4.1'
      - '1.1.4.2'
      - '1.1.4.3'
      - '1.1.4.4'
      - '3.1.1'
      - '3.1.2'
      - '3.1.3'
      - '3.2.1'
      - '3.2.2'
      - '3.3.1'
      - '3.3.2'
      - '3.3.3'
      - '3.3.4'
      - '3.3.5'
      - '3.3.6'
      - '3.3.7'
      - '3.3.8'
      - '3.3.9'
      - '3.4.1.1'
      - '3.4.1.2'
      - '3.4.2.1'
      - '3.4.2.2'
      - '3.4.2.3'
      - '3.4.2.4'
      - '3.4.2.5'
      - '3.4.2.6'
      - '3.4.2.7'

      


  tasks:
    - name: user input
      ansible.builtin.set_fact:
        "rhel9cis_rule_{{ item | replace('.','_') }}: true "
      loop: "{{ cis_remediation  }}"

    - name: Dispay all variables known for a hosts
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]


    - name: call RHEL9-CIS-devel roles
      ansible.builtin.include_role:
        name: RHEL9-CIS-devel
        


  
  