---
- hosts: all  
  become: true

  vars:
    cis_remediation:
      - '1.1.2.1'

  tasks:
    - name: user input
      ansible.builtin.set_fact:
        "rhel9cis_rule_{{ item | replace('.','_') }}: true "
      loop: "{{ cis_remediation  }}"

    - name: call RHEL9-CIS-devel roles
      ansible.builtin.include_role:
        name: RHEL9-CIS-devel
        


  
  