---
- hosts: all  
  become: true

  vars:
    cis_remediation:
      - '5.2.18'
      - '5.2.15'
      - '5.2.12'
      - '5.2.13'

  tasks:
    - name: user input
      ansible.builtin.set_fact:
        "rhel9cis_rule_{{ item | replace('.','_') }}: true "
      loop: "{{ cis_remediation  }}"

    - name: Dispay all variables known for a hosts
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]


    - name: call RHEL9-CIS-devel roles
      ansible.builtin.include_role:
        name: RHEL9-CIS-devel
        


  
  