---
- hosts: all  
  become: true

  roles:

      - role: "RHEL9-CIS-devel"
<<<<<<< HEAD:site.yml
=======

  vars:
    - rhel9cis_rule_1_1_1_1: true
    - rhel9cis_rule_1_1_1_2: true
    - rhel9cis_rule_1_1_2_1: true
    - rhel9cis_rule_1_1_2_2: true
    - rhel9cis_rule_1_1_2_3: true
    - rhel9cis_rule_1_1_2_4: true
    - rhel9cis_rule_1_1_3_1: true
    - rhel9cis_rule_1_1_3_2: true
    - rhel9cis_rule_1_1_3_3: true
    - rhel9cis_rule_1_1_4_1: true
    - rhel9cis_rule_1_1_4_2: true
    - rhel9cis_rule_1_1_4_3: true
    - rhel9cis_rule_1_1_4_4: true
    - rhel9cis_rule_1_1_5_1: true
    - rhel9cis_rule_1_1_5_2: true
    - rhel9cis_rule_1_1_5_3: true
    - rhel9cis_rule_1_1_5_4: true
    - rhel9cis_rule_1_1_6_1: true
    - rhel9cis_rule_1_1_6_2: true
    - rhel9cis_rule_1_1_6_3: true
    - rhel9cis_rule_1_1_6_4: true
    - rhel9cis_rule_1_1_7_1: true
    - rhel9cis_rule_1_1_7_2: true
    - rhel9cis_rule_1_1_7_3: true
    - rhel9cis_rule_1_1_8_1: true
    - rhel9cis_rule_1_1_8_2: true
    - rhel9cis_rule_1_1_8_3: true
    - rhel9cis_rule_1_1_8_4: true
    - rhel9cis_rule_1_1_18: true
    - rhel9cis_rule_1_1_19: true
    - rhel9cis_rule_1_1_20: true
    - rhel9cis_rule_1_1_21: true
    - rhel9cis_rule_1_1_9: true
    - rhel9cis_rule_1_2_1: true
    - rhel9cis_rule_1_2_2: true
    - rhel9cis_rule_1_2_3: true
    - rhel9cis_rule_1_2_4: true
    - rhel9cis_rule_1_3_1: true
    - rhel9cis_rule_1_3_2: true
    - rhel9cis_rule_1_3_3: true
    - rhel9cis_rule_1_4_1: true
    - rhel9cis_rule_1_4_2: true
    - rhel9cis_rule_1_5_1: true
    - rhel9cis_rule_1_5_2: true
    - rhel9cis_rule_1_5_3: true
    - rhel9cis_rule_1_6_1_1: true
    - rhel9cis_rule_1_6_1_2: true
    - rhel9cis_rule_1_6_1_3: true
    - rhel9cis_rule_1_6_1_4: true
    - rhel9cis_rule_1_6_1_5: true
    - rhel9cis_rule_1_6_1_6: true
    - rhel9cis_rule_1_6_1_7: true
    - rhel9cis_rule_1_6_1_8: true
    - rhel9cis_rule_1_7_1: true
    - rhel9cis_rule_1_7_2: true
    - rhel9cis_rule_1_7_3: true
    - rhel9cis_rule_1_7_4: true
    - rhel9cis_rule_1_7_5: true
    - rhel9cis_rule_1_7_6: true
    - rhel9cis_rule_1_8_1: true
    - rhel9cis_rule_1_8_2: true
    - rhel9cis_rule_1_8_3: true
    - rhel9cis_rule_1_8_4: true
    - rhel9cis_rule_1_8_5: true
    - rhel9cis_rule_1_8_6: true
    - rhel9cis_rule_1_8_7: true
    - rhel9cis_rule_1_8_8: true
    - rhel9cis_rule_1_8_9: true
    - rhel9cis_rule_1_8_10: true
    - rhel9cis_rule_1_9: true
    - rhel9cis_rule_1_10: true

>>>>>>> 0a88759f5050485da5683ad9fd4bed848675b5f3:roles/RHEL9-CIS-devel/site.yml
