---
- hosts: all  
  become: true

  vars:
    cis_remediation:
      - '6.1.1'
      - '6.1.2'
      - '6.1.3'
      - '6.1.4'
      - '6.1.5'
      - '6.1.6'
      - '6.1.7'
      - '6.1.8'
      - '6.1.9'
      - '6.1.10'
      - '6.1.11'
      - '6.1.12'
      - '6.1.13'
      - '6.1.14'
      - '6.1.15'
      - '6.2.1'
      - '6.2.2'
      - '6.2.3'
      - '6.2.4'
      - '6.2.5'
      - '6.2.6'
      - '6.2.7'
      - '6.2.8'
      - '6.2.9'
      - '6.2.10'
      - '6.2.11'
      - '6.2.12'
      - '6.2.13'
      - '6.2.14'
      - '6.2.15'
      

  tasks:
    - name: user input
      ansible.builtin.set_fact:
        "rhel9cis_rule_{{ item | replace('.','_') }}: true "
      loop: "{{ cis_remediation  }}"

    - name: Dispay all variables known for a hosts
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: call RHEL9-CIS-devel roles
      ansible.builtin.include_role:
        name: RHEL9-CIS-devel
        


  
  